# This is a basic workflow to help you get started with Actions

name: Sample workflow for Firebase Distribution action

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  distribute:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      #      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: build release
        run: ./gradlew assembleRelease

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: 커피챗
          file: app/build/outputs/apk/release/app-release-unsigned.apk
      # Runs a single command using the runners shell
      #      - name: Run a one-line script
      #        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      #      - name: Run a multi-line script
      #        run: |
      #          echo Add other actions to build,
      #          echo test, and deploy your project.

#              - name: Fetch firebase credential file from secrets
#                id: fetch_credential_file
#                uses: timheuer/base64-to-file@v1
#                with:
#                  encodedString: ${{ secrets.FIREBASE_CREDENTIALS }}
#                  fileName: 'firebase_credentials.json'
#
#              - name: Firebase App Distribution
#                # You may pin to the exact commit or the version.
#                # uses: wzieba/Firebase-Distribution-Github-Action@d6e3b20d53da54e1ffd2082a8132e120b5bd1bb2
#                uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
#                with:
#                  #          # App id can be found on the General Settings page
#                  appId: ${{ secrets.FIREBASE_APP_ID }}
#                  #          # Upload token - see Firebase CLI Reference
#                  token: ${{ secrets.FIREBASE_TOKEN }}
#                  #          # Service credential file
#                  serviceCredentialsFile: 'firebase_credentials.json'
#                  #          # Artifact to upload (.apk or .ipa)
#                  file: app/build/outputs/apk/release/app-release-unsigned.apk
#                  #          # Distribution groups
#                  groups: 커피챗
#                  #          # Release notes visible on release page
#                  #          releaseNotes: # optional
#                  #          # Release notes visible on release page
#                  #          releaseNotesFile: # optional
#                  #          # Flag that can included to print verbose log output.
#                  debug: false
